[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# solc_version = "./solc"
solc_version = "0.8.25"
gas_reports = ["Unoptimized", "Optimized"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
