[profile.default]
src = "src"
out = "out"
libs = ["lib"]
offline = true
solc_version = "./solc"
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
