# .github/workflows/tests.yml
name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21.1

      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Solidity compiler
        run: |
          mkdir -p ~/.solc/releases
          wget -O solc.tar.gz https://github.com/ethereum/solidity/releases/download/v0.8.4/solc-static-linux
          tar -xzf solc.tar.gz
          mv solc ~/.solc/releases/solc-v0.8.4
          ln -s ~/.solc/releases/solc-v0.8.4 ~/.solc/solc
          ~/.solc/solc --version

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run benchmarks
        run: go test -bench=. -benchmem ./...

      - name: Check test coverage
        run: |
          go test -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
